### ISSUE TITLE
Support for Laravel 10

### ISSUE THREAD

**Issue by sshaik305** [biigle/laravel-cached-openstack#3]
This is not supported for laravel 10 as dependencies like illuminate/cache ^5.1 required

**Comment by mzur** [comment]
Hi, thanks for your interest in this package. I'm sure that all you need is add `^10` to the supported versions in the composer.json. Would you like to test if this works and send a PR?

**Comment by sshaik305** [comment]
https://github.com/biigle/laravel-cached-openstack/pull/4
